package springbootmysql.demo.entity;

import java.io.Serializable;

public class Book implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.bookName
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.userId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table books
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookId
     *
     * @return the value of books.bookId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookId
     *
     * @param bookid the value for books.bookId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.bookName
     *
     * @return the value of books.bookName
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.bookName
     *
     * @param bookname the value for books.bookName
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.userId
     *
     * @return the value of books.userId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.userId
     *
     * @param userid the value for books.userId
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Apr 16 14:05:05 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bookid=").append(bookid);
        sb.append(", bookname=").append(bookname);
        sb.append(", userid=").append(userid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}